"""Stack 3 — Graph Estimator (supervised).

Each agent, from its gossiped component view, predicts the FULL global comm graph
(adjacency). Out-of-component agents are masked 'unknown' -> the estimator must
infer their links. Trained by SUPERVISED learning against the true adjacency
(privileged at train time). Decoupled from the role-picker (no RL, no shared trunk).

Data is generated by rolling out the swarm under a fixed behavior policy (compass +
degree-budget role) so the estimator sees realistic belief/true-graph pairs,
including fragmentation.

  PYTHONPATH=. .venv/bin/python -m swarm_explore.estimator --epochs 40
"""
from __future__ import annotations

import argparse
import datetime
import json
import os

import numpy as np
import jax
import jax.numpy as jnp
import optax

from .core import (action_for, bfs, clustered_spawn, collision_mask, comm_adj,
                   connected_components, first_step, make_env_world, random_wall)
from .connect import herd_target
from .swarm import _choose_target

F = 6           # node features: x, y, degree, coverage-progress, in-component, unknown
HID = 32


# ---------------- estimator network (GCN -> bilinear adjacency) ----------------
def init_params(key):
    ks = jax.random.split(key, 4)
    def w(k, a, b):
        return jax.random.normal(k, (a, b)) * (0.7 / np.sqrt(a))
    return dict(W1=w(ks[0], F, HID), W2=w(ks[1], HID, HID), We=w(ks[2], HID, HID))


def _gcn(A, X, W1, W2):
    n = A.shape[0]
    Ah = A + jnp.eye(n)
    Ah = Ah / Ah.sum(1, keepdims=True)
    H = jax.nn.relu(Ah @ (X @ W1))
    H = jax.nn.relu(Ah @ (H @ W2))
    return H


def est_fwd(p, X, A):
    """X (N,F) belief, A (N,N) believed adjacency -> predicted adjacency logits (N,N)."""
    H = _gcn(A, X, p["W1"], p["W2"])
    Z = H @ p["We"]
    return Z @ Z.T


def node_features(pos, adj, comp_set, cov_prog, H, W, n):
    X = np.zeros((n, F), np.float32)
    for j in range(n):
        if j in comp_set:
            X[j, 0] = pos[j, 0] / H; X[j, 1] = pos[j, 1] / W
            X[j, 2] = adj[j].sum() / max(1, n - 1); X[j, 3] = cov_prog[j]; X[j, 4] = 1.0
        else:
            X[j, 5] = 1.0
    return X


# ---------------- data collection (fixed behavior policy) ----------------
def collect(H, W, n, comm_r, sense_r, steps, seed, floor=1):
    """Roll out with compass(frontier) + degree-budget(relay) and record per-component
    (X_belief, A_belief, true_adj)."""
    wall = random_wall(H, W, 0.05, seed)
    positions = clustered_spawn(wall, n, comm_r, seed)
    env, world = make_env_world(H, W, wall, positions, sense_r, True)
    kb = [np.zeros((H, W)) for _ in range(n)]; seen = [np.zeros((H, W), bool) for _ in range(n)]
    goals = [None] * n; returning = np.zeros(n, bool)
    nbr_pos = [dict() for _ in range(n)]
    Xs, Abs, Trues = [], [], []
    import jax as _jax
    key = _jax.random.PRNGKey(seed + 7)
    for t in range(steps):
        pos = np.asarray(world.body.position)
        for i in range(n):
            kb[i][int(pos[i, 0]), int(pos[i, 1])] += 1.0
        vis = np.asarray(env.sensor.visibility(world))
        for i in range(n):
            seen[i] |= vis[i]
        adj = comm_adj(pos, comm_r); comps = connected_components(adj)
        for comp in comps:
            if len(comp) > 1:
                cc = np.zeros((H, W)); ss = np.zeros((H, W), bool)
                for i in comp:
                    np.maximum(cc, kb[i], out=cc); ss |= seen[i]
                for i in comp:
                    kb[i] = cc.copy(); seen[i] = ss.copy()
        for i in range(n):
            for j in range(n):
                if adj[i, j]:
                    nbr_pos[i][j] = (int(pos[j, 0]), int(pos[j, 1]))
        comp_of = {i: comp for comp in comps for i in comp}
        cov_prog = np.array([(seen[i] & ~wall & (kb[i] >= 1)).sum() / max(1, (seen[i] & ~wall).sum())
                             for i in range(n)], np.float32)
        true_adj = adj.astype(np.float32)
        for comp in comps:
            cs = set(comp)
            Xb = node_features(pos, adj, cs, cov_prog, H, W, n)
            mk = np.array([1.0 if j in cs else 0.0 for j in range(n)], np.float32)
            Ab = true_adj * mk[None, :] * mk[:, None]
            Xs.append(Xb); Abs.append(Ab); Trues.append(true_adj)
        # behavior policy: degree-budget role + compass / herd
        deg = adj.sum(1)
        actions = np.zeros(n, int)
        for i in range(n):
            src = (int(pos[i, 0]), int(pos[i, 1])); dist, parent = bfs(seen[i] & ~wall, src)
            if returning[i]:
                if deg[i] >= floor + 1:
                    returning[i] = False
            elif deg[i] < floor:
                returning[i] = True
            if returning[i]:
                g = herd_target(i, pos, adj, nbr_pos[i], seen[i], wall, dist)
            else:
                g = goals[i]
                stale = (g is None or src == g or not np.isfinite(dist[g[0], g[1]]) or kb[i][g[0], g[1]] >= 1.0)
                if stale:
                    g = _choose_target(kb[i], seen[i], wall, src, dist, [], nbr_pos[i], comm_r, 0.0)
                goals[i] = g
            if g is not None:
                actions[i] = action_for(src, first_step(parent, src, g))
        actions = collision_mask(actions, pos, wall)
        key, sk = _jax.random.split(key)
        _, world, _, _, _ = env.step(world, jnp.asarray(actions, jnp.int32), sk)
    return np.array(Xs, np.float32), np.array(Abs, np.float32), np.array(Trues, np.float32)


def _loss(p, X, A, T):
    pred = jax.vmap(lambda x, a: est_fwd(p, x, a))(X, A)
    n = T.shape[1]
    off = ~jnp.eye(n, dtype=bool)
    bce = optax.sigmoid_binary_cross_entropy(pred, T)
    return (bce * off[None]).sum() / (off.sum() * T.shape[0])


def accuracy(p, X, A, T):
    pred = jax.vmap(lambda x, a: est_fwd(p, x, a))(X, A)
    n = T.shape[1]; off = ~jnp.eye(n, dtype=bool)
    correct = ((jax.nn.sigmoid(pred) > 0.5) == (T > 0.5))
    return float((correct * off[None]).sum() / (off.sum() * T.shape[0]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--grid", type=int, default=16)
    ap.add_argument("--agents", type=int, default=4)
    ap.add_argument("--comm-r", type=int, default=5)
    ap.add_argument("--steps", type=int, default=70)
    ap.add_argument("--train-seeds", type=int, default=24)
    ap.add_argument("--lr", type=float, default=5e-3)
    a = ap.parse_args()
    H = W = a.grid; n = a.agents; sr = 3
    print(f"Stack 3 graph-estimator (supervised) @ {H}x{H}/{n}/cr{a.comm_r}/{a.steps}st", flush=True)
    # collect data
    Xtr, Atr, Ttr = [], [], []
    for s in range(a.train_seeds):
        X, A, T = collect(H, W, n, a.comm_r, sr, a.steps, s)
        Xtr.append(X); Atr.append(A); Ttr.append(T)
    Xtr = jnp.asarray(np.concatenate(Xtr)); Atr = jnp.asarray(np.concatenate(Atr)); Ttr = jnp.asarray(np.concatenate(Ttr))
    Xte = []; Ate = []; Tte = []
    for s in range(100, 105):
        X, A, T = collect(H, W, n, a.comm_r, sr, a.steps, s)
        Xte.append(X); Ate.append(A); Tte.append(T)
    Xte = jnp.asarray(np.concatenate(Xte)); Ate = jnp.asarray(np.concatenate(Ate)); Tte = jnp.asarray(np.concatenate(Tte))
    print(f"  data: {Xtr.shape[0]} train / {Xte.shape[0]} test component-states", flush=True)

    key = jax.random.PRNGKey(0); params = init_params(key)
    opt = optax.adam(a.lr); opt_state = opt.init(params)

    @jax.jit
    def step(params, opt_state, X, A, T):
        loss, g = jax.value_and_grad(_loss)(params, X, A, T)
        upd, opt_state = opt.update(g, opt_state, params)
        return optax.apply_updates(params, upd), opt_state, loss

    # baseline accuracy: predict "all connected" (trivial)
    base_acc = float(((Tte > 0.5).astype(jnp.float32) * (~jnp.eye(n, dtype=bool))[None]).sum() /
                     ((~jnp.eye(n, dtype=bool)).sum() * Tte.shape[0]))
    hist = []
    for e in range(a.epochs):
        params, opt_state, loss = step(params, opt_state, Xtr, Atr, Ttr)
        if e % 5 == 0 or e == a.epochs - 1:
            tr_acc = accuracy(params, Xtr, Atr, Ttr); te_acc = accuracy(params, Xte, Ate, Tte)
            hist.append(dict(epoch=e, loss=float(loss), train_acc=tr_acc, test_acc=te_acc))
            print(f"  epoch {e:3d}  loss {float(loss):.3f}  train-acc {tr_acc*100:.1f}%  test-acc {te_acc*100:.1f}%", flush=True)
    print(f"  (baseline 'always-linked' test-acc: {base_acc*100:.1f}%)", flush=True)

    out = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "experiments", "swarm_explore",
                                        "estimator-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")))
    os.makedirs(out, exist_ok=True)
    np.savez(os.path.join(out, "est_params.npz"), **{k: np.asarray(v) for k, v in params.items()})
    json.dump({"config": vars(a), "history": hist, "baseline_acc": base_acc},
              open(os.path.join(out, "estimator.json"), "w"), indent=2)
    print(f"saved -> {out}", flush=True)


if __name__ == "__main__":
    main()
